### ISSUE TITLE
Question about selecting Best Prevalence Interval 

### ISSUE THREAD

**Issue by jarrodscott** [microEcology/pime#3]
Hi there. Quick question about workflow strategy because I think I may be a little confused. Here are only the highlights what I am doing but I am following the workflows you provide in your ME paper

`pime.oob.error` = `0.6666667`
`pime.best.prevalence` beginning at Prevalence 50% (up to 95%), the OOB error rate (%) drops to zero. So I chose the Prevalence Interval of **50%**.

I then run `pime.error.prediction` and all looks good. Finally, I run `pime.oob.replicate`. Here is the barchart:

![ssu18_replicated oob error_plot_1](https://user-images.githubusercontent.com/16192182/93672742-b2b97080-fa70-11ea-8f51-9d34e9ba9d7e.png)

To me, the best prevalence in the graph looks like it is **60%**, instead of *50%* as determined by `pime.best.prevalence`. So my question is, based on the results of `pime.oob.replicate`, should I go back in my workflow and select a Prevalence Interval of 60% instead? Thanks!

**Comment by microEcology** [comment]
Hi Jarrod, sorry for the late reply

I think you should probably stick with 50% prevalence. We recommended the
first threshold with zero oob error as you lose the less OTUs/ASVs... In
the end is your choice whether losing more taxa or improving the prediction
error. Also the gain, here, in oob error is very marginal to justify
removing more taxa...

Hope this helps,

Priscila Dobbler

**Comment by jarrodscott** [comment]
Hi Priscila, 

No problem, not late at all. Thank you for the advise and clarification! By the way, I love PIME. This is such an amazing tool. Thanks for your contribution to the community. 

Best
Jarrod
